/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.utils.SpeakeasyMetadata;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;


public class ArchiveNamespaceRequest {

    /**
     * Archived status
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private Optional<? extends ArchiveNamespaceRequestBody> requestBody;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=namespace_name")
    private String namespaceName;

    @JsonCreator
    public ArchiveNamespaceRequest(
            Optional<? extends ArchiveNamespaceRequestBody> requestBody,
            String namespaceName) {
        Utils.checkNotNull(requestBody, "requestBody");
        Utils.checkNotNull(namespaceName, "namespaceName");
        this.requestBody = requestBody;
        this.namespaceName = namespaceName;
    }
    
    public ArchiveNamespaceRequest(
            String namespaceName) {
        this(Optional.empty(), namespaceName);
    }

    /**
     * Archived status
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ArchiveNamespaceRequestBody> requestBody() {
        return (Optional<ArchiveNamespaceRequestBody>) requestBody;
    }

    @JsonIgnore
    public String namespaceName() {
        return namespaceName;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Archived status
     */
    public ArchiveNamespaceRequest withRequestBody(ArchiveNamespaceRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.ofNullable(requestBody);
        return this;
    }

    /**
     * Archived status
     */
    public ArchiveNamespaceRequest withRequestBody(Optional<? extends ArchiveNamespaceRequestBody> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public ArchiveNamespaceRequest withNamespaceName(String namespaceName) {
        Utils.checkNotNull(namespaceName, "namespaceName");
        this.namespaceName = namespaceName;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArchiveNamespaceRequest other = (ArchiveNamespaceRequest) o;
        return 
            Objects.deepEquals(this.requestBody, other.requestBody) &&
            Objects.deepEquals(this.namespaceName, other.namespaceName);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            requestBody,
            namespaceName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ArchiveNamespaceRequest.class,
                "requestBody", requestBody,
                "namespaceName", namespaceName);
    }
    
    public final static class Builder {
 
        private Optional<? extends ArchiveNamespaceRequestBody> requestBody = Optional.empty();
 
        private String namespaceName;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Archived status
         */
        public Builder requestBody(ArchiveNamespaceRequestBody requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = Optional.ofNullable(requestBody);
            return this;
        }

        /**
         * Archived status
         */
        public Builder requestBody(Optional<? extends ArchiveNamespaceRequestBody> requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = requestBody;
            return this;
        }

        public Builder namespaceName(String namespaceName) {
            Utils.checkNotNull(namespaceName, "namespaceName");
            this.namespaceName = namespaceName;
            return this;
        }
        
        public ArchiveNamespaceRequest build() {
            return new ArchiveNamespaceRequest(
                requestBody,
                namespaceName);
        }
    }
}

