/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class ArchiveNamespaceRequestBuilder {

    private ArchiveNamespaceRequest request;
    private final SDKMethodInterfaces.MethodCallArchiveNamespace sdk;

    public ArchiveNamespaceRequestBuilder(SDKMethodInterfaces.MethodCallArchiveNamespace sdk) {
        this.sdk = sdk;
    }

    public ArchiveNamespaceRequestBuilder request(ArchiveNamespaceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ArchiveNamespaceResponse call() throws Exception {

        return sdk.setArchived(
            request);
    }
}
