/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.utils.SpeakeasyMetadata;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;


public class CheckGithubAccessRequest {

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=org")
    private String org;

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=repo")
    private String repo;

    @JsonCreator
    public CheckGithubAccessRequest(
            String org,
            String repo) {
        Utils.checkNotNull(org, "org");
        Utils.checkNotNull(repo, "repo");
        this.org = org;
        this.repo = repo;
    }

    @JsonIgnore
    public String org() {
        return org;
    }

    @JsonIgnore
    public String repo() {
        return repo;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CheckGithubAccessRequest withOrg(String org) {
        Utils.checkNotNull(org, "org");
        this.org = org;
        return this;
    }

    public CheckGithubAccessRequest withRepo(String repo) {
        Utils.checkNotNull(repo, "repo");
        this.repo = repo;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CheckGithubAccessRequest other = (CheckGithubAccessRequest) o;
        return 
            Objects.deepEquals(this.org, other.org) &&
            Objects.deepEquals(this.repo, other.repo);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            org,
            repo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CheckGithubAccessRequest.class,
                "org", org,
                "repo", repo);
    }
    
    public final static class Builder {
 
        private String org;
 
        private String repo;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder org(String org) {
            Utils.checkNotNull(org, "org");
            this.org = org;
            return this;
        }

        public Builder repo(String repo) {
            Utils.checkNotNull(repo, "repo");
            this.repo = repo;
            return this;
        }
        
        public CheckGithubAccessRequest build() {
            return new CheckGithubAccessRequest(
                org,
                repo);
        }
    }
}

