/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class CreateWorkspaceTokenRequestBuilder {

    private CreateWorkspaceTokenRequest request;
    private final SDKMethodInterfaces.MethodCallCreateWorkspaceToken sdk;

    public CreateWorkspaceTokenRequestBuilder(SDKMethodInterfaces.MethodCallCreateWorkspaceToken sdk) {
        this.sdk = sdk;
    }

    public CreateWorkspaceTokenRequestBuilder request(CreateWorkspaceTokenRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateWorkspaceTokenResponse call() throws Exception {

        return sdk.createToken(
            request);
    }
}
