/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.models.shared.Workspace;
import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class CreateWorkspaceRequestBuilder {

    private Workspace request;
    private final SDKMethodInterfaces.MethodCallCreateWorkspace sdk;

    public CreateWorkspaceRequestBuilder(SDKMethodInterfaces.MethodCallCreateWorkspace sdk) {
        this.sdk = sdk;
    }

    public CreateWorkspaceRequestBuilder request(Workspace request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateWorkspaceResponse call() throws Exception {

        return sdk.create(
            request);
    }
}
