/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class DeleteWorkspaceTokenRequestBuilder {

    private DeleteWorkspaceTokenRequest request;
    private final SDKMethodInterfaces.MethodCallDeleteWorkspaceToken sdk;

    public DeleteWorkspaceTokenRequestBuilder(SDKMethodInterfaces.MethodCallDeleteWorkspaceToken sdk) {
        this.sdk = sdk;
    }

    public DeleteWorkspaceTokenRequestBuilder request(DeleteWorkspaceTokenRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public DeleteWorkspaceTokenResponse call() throws Exception {

        return sdk.deleteToken(
            request);
    }
}
