/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.utils.Response;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class GenerateCodeSamplePreviewResponse implements Response {

    /**
     * Successfully returned codeSample overlay file
     */
    private Optional<? extends InputStream> twoHundredApplicationJsonResponseStream;

    /**
     * Successfully returned codeSample overlay file
     */
    private Optional<? extends InputStream> twoHundredApplicationXYamlResponseStream;

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public GenerateCodeSamplePreviewResponse(
            Optional<? extends InputStream> twoHundredApplicationJsonResponseStream,
            Optional<? extends InputStream> twoHundredApplicationXYamlResponseStream,
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(twoHundredApplicationJsonResponseStream, "twoHundredApplicationJsonResponseStream");
        Utils.checkNotNull(twoHundredApplicationXYamlResponseStream, "twoHundredApplicationXYamlResponseStream");
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.twoHundredApplicationJsonResponseStream = twoHundredApplicationJsonResponseStream;
        this.twoHundredApplicationXYamlResponseStream = twoHundredApplicationXYamlResponseStream;
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public GenerateCodeSamplePreviewResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(Optional.empty(), Optional.empty(), contentType, statusCode, rawResponse);
    }

    /**
     * Successfully returned codeSample overlay file
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<InputStream> twoHundredApplicationJsonResponseStream() {
        return (Optional<InputStream>) twoHundredApplicationJsonResponseStream;
    }

    /**
     * Successfully returned codeSample overlay file
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<InputStream> twoHundredApplicationXYamlResponseStream() {
        return (Optional<InputStream>) twoHundredApplicationXYamlResponseStream;
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Successfully returned codeSample overlay file
     */
    public GenerateCodeSamplePreviewResponse withTwoHundredApplicationJsonResponseStream(InputStream twoHundredApplicationJsonResponseStream) {
        Utils.checkNotNull(twoHundredApplicationJsonResponseStream, "twoHundredApplicationJsonResponseStream");
        this.twoHundredApplicationJsonResponseStream = Optional.ofNullable(twoHundredApplicationJsonResponseStream);
        return this;
    }

    /**
     * Successfully returned codeSample overlay file
     */
    public GenerateCodeSamplePreviewResponse withTwoHundredApplicationJsonResponseStream(Optional<? extends InputStream> twoHundredApplicationJsonResponseStream) {
        Utils.checkNotNull(twoHundredApplicationJsonResponseStream, "twoHundredApplicationJsonResponseStream");
        this.twoHundredApplicationJsonResponseStream = twoHundredApplicationJsonResponseStream;
        return this;
    }

    /**
     * Successfully returned codeSample overlay file
     */
    public GenerateCodeSamplePreviewResponse withTwoHundredApplicationXYamlResponseStream(InputStream twoHundredApplicationXYamlResponseStream) {
        Utils.checkNotNull(twoHundredApplicationXYamlResponseStream, "twoHundredApplicationXYamlResponseStream");
        this.twoHundredApplicationXYamlResponseStream = Optional.ofNullable(twoHundredApplicationXYamlResponseStream);
        return this;
    }

    /**
     * Successfully returned codeSample overlay file
     */
    public GenerateCodeSamplePreviewResponse withTwoHundredApplicationXYamlResponseStream(Optional<? extends InputStream> twoHundredApplicationXYamlResponseStream) {
        Utils.checkNotNull(twoHundredApplicationXYamlResponseStream, "twoHundredApplicationXYamlResponseStream");
        this.twoHundredApplicationXYamlResponseStream = twoHundredApplicationXYamlResponseStream;
        return this;
    }

    /**
     * HTTP response content type for this operation
     */
    public GenerateCodeSamplePreviewResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GenerateCodeSamplePreviewResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GenerateCodeSamplePreviewResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GenerateCodeSamplePreviewResponse other = (GenerateCodeSamplePreviewResponse) o;
        return 
            Objects.deepEquals(this.twoHundredApplicationJsonResponseStream, other.twoHundredApplicationJsonResponseStream) &&
            Objects.deepEquals(this.twoHundredApplicationXYamlResponseStream, other.twoHundredApplicationXYamlResponseStream) &&
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            twoHundredApplicationJsonResponseStream,
            twoHundredApplicationXYamlResponseStream,
            contentType,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GenerateCodeSamplePreviewResponse.class,
                "twoHundredApplicationJsonResponseStream", twoHundredApplicationJsonResponseStream,
                "twoHundredApplicationXYamlResponseStream", twoHundredApplicationXYamlResponseStream,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private Optional<? extends InputStream> twoHundredApplicationJsonResponseStream = Optional.empty();
 
        private Optional<? extends InputStream> twoHundredApplicationXYamlResponseStream = Optional.empty();
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Successfully returned codeSample overlay file
         */
        public Builder twoHundredApplicationJsonResponseStream(InputStream twoHundredApplicationJsonResponseStream) {
            Utils.checkNotNull(twoHundredApplicationJsonResponseStream, "twoHundredApplicationJsonResponseStream");
            this.twoHundredApplicationJsonResponseStream = Optional.ofNullable(twoHundredApplicationJsonResponseStream);
            return this;
        }

        /**
         * Successfully returned codeSample overlay file
         */
        public Builder twoHundredApplicationJsonResponseStream(Optional<? extends InputStream> twoHundredApplicationJsonResponseStream) {
            Utils.checkNotNull(twoHundredApplicationJsonResponseStream, "twoHundredApplicationJsonResponseStream");
            this.twoHundredApplicationJsonResponseStream = twoHundredApplicationJsonResponseStream;
            return this;
        }

        /**
         * Successfully returned codeSample overlay file
         */
        public Builder twoHundredApplicationXYamlResponseStream(InputStream twoHundredApplicationXYamlResponseStream) {
            Utils.checkNotNull(twoHundredApplicationXYamlResponseStream, "twoHundredApplicationXYamlResponseStream");
            this.twoHundredApplicationXYamlResponseStream = Optional.ofNullable(twoHundredApplicationXYamlResponseStream);
            return this;
        }

        /**
         * Successfully returned codeSample overlay file
         */
        public Builder twoHundredApplicationXYamlResponseStream(Optional<? extends InputStream> twoHundredApplicationXYamlResponseStream) {
            Utils.checkNotNull(twoHundredApplicationXYamlResponseStream, "twoHundredApplicationXYamlResponseStream");
            this.twoHundredApplicationXYamlResponseStream = twoHundredApplicationXYamlResponseStream;
            return this;
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public GenerateCodeSamplePreviewResponse build() {
            return new GenerateCodeSamplePreviewResponse(
                twoHundredApplicationJsonResponseStream,
                twoHundredApplicationXYamlResponseStream,
                contentType,
                statusCode,
                rawResponse);
        }
    }
}

