/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.utils.Response;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class GetRevisionsResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * OK
     */
    private Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse> getRevisionsResponse;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public GetRevisionsResponse(
            String contentType,
            Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse> getRevisionsResponse,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(getRevisionsResponse, "getRevisionsResponse");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.getRevisionsResponse = getRevisionsResponse;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public GetRevisionsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse> getRevisionsResponse() {
        return (Optional<dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse>) getRevisionsResponse;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetRevisionsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * OK
     */
    public GetRevisionsResponse withGetRevisionsResponse(dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse getRevisionsResponse) {
        Utils.checkNotNull(getRevisionsResponse, "getRevisionsResponse");
        this.getRevisionsResponse = Optional.ofNullable(getRevisionsResponse);
        return this;
    }

    /**
     * OK
     */
    public GetRevisionsResponse withGetRevisionsResponse(Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse> getRevisionsResponse) {
        Utils.checkNotNull(getRevisionsResponse, "getRevisionsResponse");
        this.getRevisionsResponse = getRevisionsResponse;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetRevisionsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetRevisionsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetRevisionsResponse other = (GetRevisionsResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.getRevisionsResponse, other.getRevisionsResponse) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            getRevisionsResponse,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetRevisionsResponse.class,
                "contentType", contentType,
                "getRevisionsResponse", getRevisionsResponse,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse> getRevisionsResponse = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * OK
         */
        public Builder getRevisionsResponse(dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse getRevisionsResponse) {
            Utils.checkNotNull(getRevisionsResponse, "getRevisionsResponse");
            this.getRevisionsResponse = Optional.ofNullable(getRevisionsResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder getRevisionsResponse(Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.GetRevisionsResponse> getRevisionsResponse) {
            Utils.checkNotNull(getRevisionsResponse, "getRevisionsResponse");
            this.getRevisionsResponse = getRevisionsResponse;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public GetRevisionsResponse build() {
            return new GetRevisionsResponse(
                contentType,
                getRevisionsResponse,
                statusCode,
                rawResponse);
        }
    }
}

