/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import java.lang.Exception;

public class GetValidEmbedAccessTokensRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetValidEmbedAccessTokens sdk;

    public GetValidEmbedAccessTokensRequestBuilder(SDKMethodInterfaces.MethodCallGetValidEmbedAccessTokens sdk) {
        this.sdk = sdk;
    }

    public GetValidEmbedAccessTokensResponse call() throws Exception {

        return sdk.getValidEmbedAccessTokensDirect();
    }
}
