/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.utils.SpeakeasyMetadata;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.Optional;


public class GetWorkspaceTargetsRequest {

    /**
     * Filter to only return targets with events created after this timestamp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=after_last_event_created_at")
    private Optional<OffsetDateTime> afterLastEventCreatedAt;

    @JsonCreator
    public GetWorkspaceTargetsRequest(
            Optional<OffsetDateTime> afterLastEventCreatedAt) {
        Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
        this.afterLastEventCreatedAt = afterLastEventCreatedAt;
    }
    
    public GetWorkspaceTargetsRequest() {
        this(Optional.empty());
    }

    /**
     * Filter to only return targets with events created after this timestamp
     */
    @JsonIgnore
    public Optional<OffsetDateTime> afterLastEventCreatedAt() {
        return afterLastEventCreatedAt;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Filter to only return targets with events created after this timestamp
     */
    public GetWorkspaceTargetsRequest withAfterLastEventCreatedAt(OffsetDateTime afterLastEventCreatedAt) {
        Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
        this.afterLastEventCreatedAt = Optional.ofNullable(afterLastEventCreatedAt);
        return this;
    }

    /**
     * Filter to only return targets with events created after this timestamp
     */
    public GetWorkspaceTargetsRequest withAfterLastEventCreatedAt(Optional<OffsetDateTime> afterLastEventCreatedAt) {
        Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
        this.afterLastEventCreatedAt = afterLastEventCreatedAt;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceTargetsRequest other = (GetWorkspaceTargetsRequest) o;
        return 
            Objects.deepEquals(this.afterLastEventCreatedAt, other.afterLastEventCreatedAt);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            afterLastEventCreatedAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceTargetsRequest.class,
                "afterLastEventCreatedAt", afterLastEventCreatedAt);
    }
    
    public final static class Builder {
 
        private Optional<OffsetDateTime> afterLastEventCreatedAt = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Filter to only return targets with events created after this timestamp
         */
        public Builder afterLastEventCreatedAt(OffsetDateTime afterLastEventCreatedAt) {
            Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
            this.afterLastEventCreatedAt = Optional.ofNullable(afterLastEventCreatedAt);
            return this;
        }

        /**
         * Filter to only return targets with events created after this timestamp
         */
        public Builder afterLastEventCreatedAt(Optional<OffsetDateTime> afterLastEventCreatedAt) {
            Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
            this.afterLastEventCreatedAt = afterLastEventCreatedAt;
            return this;
        }
        
        public GetWorkspaceTargetsRequest build() {
            return new GetWorkspaceTargetsRequest(
                afterLastEventCreatedAt);
        }
    }
}

