/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


public class GetWorkspacesRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetWorkspaces sdk;

    public GetWorkspacesRequestBuilder(SDKMethodInterfaces.MethodCallGetWorkspaces sdk) {
        this.sdk = sdk;
    }

    public GetWorkspacesResponse call() throws Exception {

        return sdk.getAllDirect();
    }
}
