/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.utils.SpeakeasyMetadata;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.Optional;


public class GetWorkspaceTargetsDeprecatedRequest {

    /**
     * Filter to only return targets with events created after this timestamp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=after_last_event_created_at")
    private Optional<OffsetDateTime> afterLastEventCreatedAt;

    /**
     * Unique identifier of the workspace.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspace_id")
    private Optional<String> workspaceId;

    @JsonCreator
    public GetWorkspaceTargetsDeprecatedRequest(
            Optional<OffsetDateTime> afterLastEventCreatedAt,
            Optional<String> workspaceId) {
        Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.afterLastEventCreatedAt = afterLastEventCreatedAt;
        this.workspaceId = workspaceId;
    }
    
    public GetWorkspaceTargetsDeprecatedRequest() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * Filter to only return targets with events created after this timestamp
     */
    @JsonIgnore
    public Optional<OffsetDateTime> afterLastEventCreatedAt() {
        return afterLastEventCreatedAt;
    }

    /**
     * Unique identifier of the workspace.
     */
    @JsonIgnore
    public Optional<String> workspaceId() {
        return workspaceId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Filter to only return targets with events created after this timestamp
     */
    public GetWorkspaceTargetsDeprecatedRequest withAfterLastEventCreatedAt(OffsetDateTime afterLastEventCreatedAt) {
        Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
        this.afterLastEventCreatedAt = Optional.ofNullable(afterLastEventCreatedAt);
        return this;
    }

    /**
     * Filter to only return targets with events created after this timestamp
     */
    public GetWorkspaceTargetsDeprecatedRequest withAfterLastEventCreatedAt(Optional<OffsetDateTime> afterLastEventCreatedAt) {
        Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
        this.afterLastEventCreatedAt = afterLastEventCreatedAt;
        return this;
    }

    /**
     * Unique identifier of the workspace.
     */
    public GetWorkspaceTargetsDeprecatedRequest withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = Optional.ofNullable(workspaceId);
        return this;
    }

    /**
     * Unique identifier of the workspace.
     */
    public GetWorkspaceTargetsDeprecatedRequest withWorkspaceId(Optional<String> workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceTargetsDeprecatedRequest other = (GetWorkspaceTargetsDeprecatedRequest) o;
        return 
            Objects.deepEquals(this.afterLastEventCreatedAt, other.afterLastEventCreatedAt) &&
            Objects.deepEquals(this.workspaceId, other.workspaceId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            afterLastEventCreatedAt,
            workspaceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceTargetsDeprecatedRequest.class,
                "afterLastEventCreatedAt", afterLastEventCreatedAt,
                "workspaceId", workspaceId);
    }
    
    public final static class Builder {
 
        private Optional<OffsetDateTime> afterLastEventCreatedAt = Optional.empty();
 
        private Optional<String> workspaceId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Filter to only return targets with events created after this timestamp
         */
        public Builder afterLastEventCreatedAt(OffsetDateTime afterLastEventCreatedAt) {
            Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
            this.afterLastEventCreatedAt = Optional.ofNullable(afterLastEventCreatedAt);
            return this;
        }

        /**
         * Filter to only return targets with events created after this timestamp
         */
        public Builder afterLastEventCreatedAt(Optional<OffsetDateTime> afterLastEventCreatedAt) {
            Utils.checkNotNull(afterLastEventCreatedAt, "afterLastEventCreatedAt");
            this.afterLastEventCreatedAt = afterLastEventCreatedAt;
            return this;
        }

        /**
         * Unique identifier of the workspace.
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = Optional.ofNullable(workspaceId);
            return this;
        }

        /**
         * Unique identifier of the workspace.
         */
        public Builder workspaceId(Optional<String> workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }
        
        public GetWorkspaceTargetsDeprecatedRequest build() {
            return new GetWorkspaceTargetsDeprecatedRequest(
                afterLastEventCreatedAt,
                workspaceId);
        }
    }
}

