/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.models.shared.GithubTriggerActionRequest;
import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class GithubTriggerActionRequestBuilder {

    private GithubTriggerActionRequest request;
    private final SDKMethodInterfaces.MethodCallGithubTriggerAction sdk;

    public GithubTriggerActionRequestBuilder(SDKMethodInterfaces.MethodCallGithubTriggerAction sdk) {
        this.sdk = sdk;
    }

    public GithubTriggerActionRequestBuilder request(GithubTriggerActionRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GithubTriggerActionResponse call() throws Exception {

        return sdk.triggerAction(
            request);
    }
}
