/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.models.shared.GithubConfigureMintlifyRepoRequest;
import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class GithubConfigureMintlifyRepoRequestBuilder {

    private GithubConfigureMintlifyRepoRequest request;
    private final SDKMethodInterfaces.MethodCallGithubConfigureMintlifyRepo sdk;

    public GithubConfigureMintlifyRepoRequestBuilder(SDKMethodInterfaces.MethodCallGithubConfigureMintlifyRepo sdk) {
        this.sdk = sdk;
    }

    public GithubConfigureMintlifyRepoRequestBuilder request(GithubConfigureMintlifyRepoRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GithubConfigureMintlifyRepoResponse call() throws Exception {

        return sdk.configureMintlifyRepo(
            request);
    }
}
