/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class GrantUserAccessToWorkspaceRequestBuilder {

    private GrantUserAccessToWorkspaceRequest request;
    private final SDKMethodInterfaces.MethodCallGrantUserAccessToWorkspace sdk;

    public GrantUserAccessToWorkspaceRequestBuilder(SDKMethodInterfaces.MethodCallGrantUserAccessToWorkspace sdk) {
        this.sdk = sdk;
    }

    public GrantUserAccessToWorkspaceRequestBuilder request(GrantUserAccessToWorkspaceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GrantUserAccessToWorkspaceResponse call() throws Exception {

        return sdk.grantAccess(
            request);
    }
}
