/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class LinkGithubAccessRequestBuilder {

    private LinkGithubAccessRequest request;
    private final SDKMethodInterfaces.MethodCallLinkGithubAccess sdk;

    public LinkGithubAccessRequestBuilder(SDKMethodInterfaces.MethodCallLinkGithubAccess sdk) {
        this.sdk = sdk;
    }

    public LinkGithubAccessRequestBuilder request(LinkGithubAccessRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public LinkGithubAccessResponse call() throws Exception {

        return sdk.linkGithub(
            request);
    }
}
