/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class ListRemoteSourcesRequestBuilder {

    private ListRemoteSourcesRequest request;
    private final SDKMethodInterfaces.MethodCallListRemoteSources sdk;

    public ListRemoteSourcesRequestBuilder(SDKMethodInterfaces.MethodCallListRemoteSources sdk) {
        this.sdk = sdk;
    }

    public ListRemoteSourcesRequestBuilder request(ListRemoteSourcesRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ListRemoteSourcesResponse call() throws Exception {

        return sdk.listRemoteSources(
            request);
    }
}
