/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.models.shared.SuggestItemsRequestBody;
import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class SuggestItemsRequestBuilder {

    private SuggestItemsRequestBody request;
    private final SDKMethodInterfaces.MethodCallSuggestItems sdk;

    public SuggestItemsRequestBuilder(SDKMethodInterfaces.MethodCallSuggestItems sdk) {
        this.sdk = sdk;
    }

    public SuggestItemsRequestBuilder request(SuggestItemsRequestBody request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public SuggestItemsResponse call() throws Exception {

        return sdk.suggestItems(
            request);
    }
}
