/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.models.shared.WorkspaceSettings;
import dev.speakeasyapi.javaclientsdk.utils.SpeakeasyMetadata;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;


public class UpdateWorkspaceSettingsRequest {

    /**
     * The workspace settings to update.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private WorkspaceSettings workspaceSettings;

    /**
     * Unique identifier of the workspace.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspace_id")
    private Optional<String> workspaceId;

    @JsonCreator
    public UpdateWorkspaceSettingsRequest(
            WorkspaceSettings workspaceSettings,
            Optional<String> workspaceId) {
        Utils.checkNotNull(workspaceSettings, "workspaceSettings");
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceSettings = workspaceSettings;
        this.workspaceId = workspaceId;
    }
    
    public UpdateWorkspaceSettingsRequest(
            WorkspaceSettings workspaceSettings) {
        this(workspaceSettings, Optional.empty());
    }

    /**
     * The workspace settings to update.
     */
    @JsonIgnore
    public WorkspaceSettings workspaceSettings() {
        return workspaceSettings;
    }

    /**
     * Unique identifier of the workspace.
     */
    @JsonIgnore
    public Optional<String> workspaceId() {
        return workspaceId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The workspace settings to update.
     */
    public UpdateWorkspaceSettingsRequest withWorkspaceSettings(WorkspaceSettings workspaceSettings) {
        Utils.checkNotNull(workspaceSettings, "workspaceSettings");
        this.workspaceSettings = workspaceSettings;
        return this;
    }

    /**
     * Unique identifier of the workspace.
     */
    public UpdateWorkspaceSettingsRequest withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = Optional.ofNullable(workspaceId);
        return this;
    }

    /**
     * Unique identifier of the workspace.
     */
    public UpdateWorkspaceSettingsRequest withWorkspaceId(Optional<String> workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateWorkspaceSettingsRequest other = (UpdateWorkspaceSettingsRequest) o;
        return 
            Objects.deepEquals(this.workspaceSettings, other.workspaceSettings) &&
            Objects.deepEquals(this.workspaceId, other.workspaceId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            workspaceSettings,
            workspaceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateWorkspaceSettingsRequest.class,
                "workspaceSettings", workspaceSettings,
                "workspaceId", workspaceId);
    }
    
    public final static class Builder {
 
        private WorkspaceSettings workspaceSettings;
 
        private Optional<String> workspaceId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The workspace settings to update.
         */
        public Builder workspaceSettings(WorkspaceSettings workspaceSettings) {
            Utils.checkNotNull(workspaceSettings, "workspaceSettings");
            this.workspaceSettings = workspaceSettings;
            return this;
        }

        /**
         * Unique identifier of the workspace.
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = Optional.ofNullable(workspaceId);
            return this;
        }

        /**
         * Unique identifier of the workspace.
         */
        public Builder workspaceId(Optional<String> workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }
        
        public UpdateWorkspaceSettingsRequest build() {
            return new UpdateWorkspaceSettingsRequest(
                workspaceSettings,
                workspaceId);
        }
    }
}

