/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class UpdateWorkspaceSettingsRequestBuilder {

    private UpdateWorkspaceSettingsRequest request;
    private final SDKMethodInterfaces.MethodCallUpdateWorkspaceSettings sdk;

    public UpdateWorkspaceSettingsRequestBuilder(SDKMethodInterfaces.MethodCallUpdateWorkspaceSettings sdk) {
        this.sdk = sdk;
    }

    public UpdateWorkspaceSettingsRequestBuilder request(UpdateWorkspaceSettingsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UpdateWorkspaceSettingsResponse call() throws Exception {

        return sdk.updateSettings(
            request);
    }
}
