workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/chase-test/chase-test/my-source-new
targets:
    java-target:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
                useSonatypeLegacy: true
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/chase-test/chase-test/my-source-java-code-samples
