workflowVersion: 1.0.0
speakeasyVersion: 1.256.1
sources:
    my-source:
        inputs:
            - location: https://docs.speakeasyapi.dev/openapi.yaml
targets:
    java-target:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
