/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * FeatureFlag - A feature flag is a key-value pair that can be used to enable or disable features.
 */

public class FeatureFlag {

    /**
     * enum value workspace feature flag
     */
    @JsonProperty("feature_flag")
    private WorkspaceFeatureFlag featureFlag;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("trial_ends_at")
    private JsonNullable<OffsetDateTime> trialEndsAt;

    @JsonCreator
    public FeatureFlag(
            @JsonProperty("feature_flag") WorkspaceFeatureFlag featureFlag,
            @JsonProperty("trial_ends_at") JsonNullable<OffsetDateTime> trialEndsAt) {
        Utils.checkNotNull(featureFlag, "featureFlag");
        Utils.checkNotNull(trialEndsAt, "trialEndsAt");
        this.featureFlag = featureFlag;
        this.trialEndsAt = trialEndsAt;
    }
    
    public FeatureFlag(
            WorkspaceFeatureFlag featureFlag) {
        this(featureFlag, JsonNullable.undefined());
    }

    /**
     * enum value workspace feature flag
     */
    @JsonIgnore
    public WorkspaceFeatureFlag featureFlag() {
        return featureFlag;
    }

    @JsonIgnore
    public JsonNullable<OffsetDateTime> trialEndsAt() {
        return trialEndsAt;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * enum value workspace feature flag
     */
    public FeatureFlag withFeatureFlag(WorkspaceFeatureFlag featureFlag) {
        Utils.checkNotNull(featureFlag, "featureFlag");
        this.featureFlag = featureFlag;
        return this;
    }

    public FeatureFlag withTrialEndsAt(OffsetDateTime trialEndsAt) {
        Utils.checkNotNull(trialEndsAt, "trialEndsAt");
        this.trialEndsAt = JsonNullable.of(trialEndsAt);
        return this;
    }

    public FeatureFlag withTrialEndsAt(JsonNullable<OffsetDateTime> trialEndsAt) {
        Utils.checkNotNull(trialEndsAt, "trialEndsAt");
        this.trialEndsAt = trialEndsAt;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FeatureFlag other = (FeatureFlag) o;
        return 
            Objects.deepEquals(this.featureFlag, other.featureFlag) &&
            Objects.deepEquals(this.trialEndsAt, other.trialEndsAt);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            featureFlag,
            trialEndsAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FeatureFlag.class,
                "featureFlag", featureFlag,
                "trialEndsAt", trialEndsAt);
    }
    
    public final static class Builder {
 
        private WorkspaceFeatureFlag featureFlag;
 
        private JsonNullable<OffsetDateTime> trialEndsAt = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * enum value workspace feature flag
         */
        public Builder featureFlag(WorkspaceFeatureFlag featureFlag) {
            Utils.checkNotNull(featureFlag, "featureFlag");
            this.featureFlag = featureFlag;
            return this;
        }

        public Builder trialEndsAt(OffsetDateTime trialEndsAt) {
            Utils.checkNotNull(trialEndsAt, "trialEndsAt");
            this.trialEndsAt = JsonNullable.of(trialEndsAt);
            return this;
        }

        public Builder trialEndsAt(JsonNullable<OffsetDateTime> trialEndsAt) {
            Utils.checkNotNull(trialEndsAt, "trialEndsAt");
            this.trialEndsAt = trialEndsAt;
            return this;
        }
        
        public FeatureFlag build() {
            return new FeatureFlag(
                featureFlag,
                trialEndsAt);
        }
    }
}

