/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package dev.speakeasyapi.javaclientsdk.models.shared;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
/**
 * GenerateBumpType - Bump type of the lock file (calculated semver delta, or a custom change (manual release))
 */
public enum GenerateBumpType {
    MAJOR("major"),
    MINOR("minor"),
    PATCH("patch"),
    CUSTOM("custom"),
    NONE("none");

    @JsonValue
    private final String value;

    private GenerateBumpType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GenerateBumpType> fromValue(String value) {
        for (GenerateBumpType o: GenerateBumpType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
