/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum Level {
    ALLOWED("allowed"),
    WARNING("warning"),
    BLOCKED("blocked");

    @JsonValue
    private final String value;

    private Level(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Level> fromValue(String value) {
        for (Level o: Level.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
