/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;


public class Relationship {

    @JsonProperty("user_id")
    private String userId;

    @JsonProperty("workspace_id")
    private String workspaceId;

    @JsonCreator
    public Relationship(
            @JsonProperty("user_id") String userId,
            @JsonProperty("workspace_id") String workspaceId) {
        Utils.checkNotNull(userId, "userId");
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.userId = userId;
        this.workspaceId = workspaceId;
    }

    @JsonIgnore
    public String userId() {
        return userId;
    }

    @JsonIgnore
    public String workspaceId() {
        return workspaceId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public Relationship withUserId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public Relationship withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Relationship other = (Relationship) o;
        return 
            Objects.deepEquals(this.userId, other.userId) &&
            Objects.deepEquals(this.workspaceId, other.workspaceId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            userId,
            workspaceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Relationship.class,
                "userId", userId,
                "workspaceId", workspaceId);
    }
    
    public final static class Builder {
 
        private String userId;
 
        private String workspaceId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder userId(String userId) {
            Utils.checkNotNull(userId, "userId");
            this.userId = userId;
            return this;
        }

        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }
        
        public Relationship build() {
            return new Relationship(
                userId,
                workspaceId);
        }
    }
}

