/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum RevisionContentsMetadataType {
    OPENAPI_BUNDLE("OPENAPI_BUNDLE"),
    OPENAPI_OVERLAY("OPENAPI_OVERLAY");

    @JsonValue
    private final String value;

    private RevisionContentsMetadataType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<RevisionContentsMetadataType> fromValue(String value) {
        for (RevisionContentsMetadataType o: RevisionContentsMetadataType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
