name: Generate
"on":
    workflow_dispatch:
        inputs:
            force:
                description: Force the generation of the SDKs
                type: boolean
                default: false
    schedule:
        - cron: 0 0 * * *
jobs:
    generate:
        uses: speakeasy-api/sdk-generation-action-v15/.github/workflows/workflow-executor.yaml@v15
        with:
            force: ${{ github.event.inputs.force }}
            mode: direct
            speakeasy_version: latest
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            java_gpg_passphrase: ${{ secrets.PGP_PASSPHRASE }}
            java_gpg_secret_key: ${{ secrets.PGP_SECRET_KEY }}
            ossrh_password: ${{ secrets.SONATYPE_PASSWORD }}
            ossrh_username: ${{ secrets.SONATYPE_USERNAME }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
