name: Generate
on:
    workflow_dispatch:
        inputs:
            force:
                description: "Force the generation of the SDKs"
                type: boolean
                default: false
    schedule:
        - cron: 0 0 * * *

jobs:
    generate:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15.1.0
        with:
            speakeasy_version: latest
            use_sonatype_central: true
            force: ${{ github.event.inputs.force }}
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
            ossrh_username: ${{ secrets.SONATYPE_USERNAME }}
            ossrh_password: ${{ secrets.SONATYPE_PASSWORD }}
            java_gpg_secret_key: ${{ secrets.PGP_SECRET_KEY }}
            java_gpg_passphrase: ${{ secrets.PGP_PASSPHRASE }}
