name: Generate

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *

jobs:
  generate:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - uses: speakeasy-api/sdk-generation-action@v11.1
        with:
          speakeasy_version: latest
          openapi_doc_location: https://docs.speakeasyapi.dev/openapi.yaml
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          languages: |-
            - java
          publish_java: true
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          force: ${{ github.event.inputs.force }}
          ossrh_username: ${{ secrets.SONATYPE_USERNAME }}
          ossrh_password: ${{ secrets.SONATYPE_PASSWORD }}
