name: Tag
on:
  push:
    branches:
      - main

jobs:
    tag:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/tag.yaml@v15
        with:
            registry_tags: chase-main
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          
